services:
  redis:
    image: redis:6.2-alpine3.14
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3

  wait-for-redis:
    image: willwill/wait-for-it
    command: redis:6379 -t 30
    depends_on:
      redis:
        condition: service_healthy

  cassandra:
    image: bitnami/cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - ./cassandra/initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: cqlsh -u cassandra -p cassandra -k shortener
      interval: 15s
      timeout: 10s
      retries: 6

  wait-for-cassandra:
    image: willwill/wait-for-it
    command: cassandra:9042 -t 60
    depends_on:
      cassandra:
        condition: service_healthy

  shortener:
    image: quantonganh/shortener:main
    container_name: shortener
    ports:
      - 8080:8080
    volumes:
      - ./config.yml:/config.yml
    depends_on:
      - wait-for-redis
      - wait-for-cassandra