name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29

    - name: Test
      run: make test
        
    - name: Build
      run: |-
        make frontend
        make build

    - name: Set up QEMU
      if: github.event_name == 'push'
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      if: github.event_name == 'push'
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: github.event_name == 'push'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm/v8
        tags: ${{ github.repository }}:main

  integration-test:
    if: github.event_name == 'push'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run integration test
        run: |-
          docker-compose up -d
          make integration-test

      - name: Display logs
        if: failure()
        run: |-
          docker inspect --format "{{ json .State.Health }}" shortener_cassandra_1 | jq
          docker-compose logs